### ISSUE TITLE
Corrupted Archive

### ISSUE THREAD

**Issue by Zang00se** [BRN101/MID-FIGHT_MASSES_KE_master#1]
So whenever I go into winrar it says the archive is corrupted, I ignore it but if I try to extract it, well.... It won't let me.

Please fix this.

**Comment by BRN101** [comment]
What? It works
Or what do you mean?

**Comment by Zang00se** [comment]
Like it won't let me extract due to the .zip file being corrupted, I tried downloading it twice, and still was corrupted.

**Comment by BRN101** [comment]
If you can't extract the zip maybe it's your winrar

**Comment by Zang00se** [comment]
I'll try a different way of getting it to extract

**Comment by Zang00se** [comment]
I think it works now, it's on my desktop

**Comment by BRN101** [comment]
yes yes
